name: ee-tools
channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh>=1.0.0
  - earthengine-api>=0.1.390
  - gdal>=3.6,<4.0
  - matplotlib>=2.1.0
  - numpy>=1.15.0
  - openpyxl
  - pandas>=0.23.0
  - pytest
  - python=3.9
  - requests
  - scikit-learn
  - scipy
